### ISSUE TITLE
First findings after intallation and try to make Dropbox test 4.0.ALPHA.1 operational

### ISSUE THREAD

**Issue by StephanEd75** [JankariTech/DropboxExtensionForJoomlaPublic#1]
After intalling a very minor issue; Joomla tells 2x intallation correct completed (in dutch: installatie geslaagd).

When trying to make an correct map to display I got the error 0-Fout: 0
Looking to the filemap the first letter was different (uppercase). Correcting to the new one seems not good.

So, now the errror:
{"error_summary": "invalid_access_token/..", "error": {".tag": "invalid_access_token"}}

Trying to check some things... first make an new dropbox map and try if it could work, yes.
Everything goes good. (2x save succesfull)
   Bericht:
   Item opslaan geslaagd.
   Item opslaan geslaagd.
Now, trying to fix de first map, and yes. after rename, disconnnect and connect it works.

==> for our functionality everything looks fine.

Go futher, in de front uploading files (pdf).
I choose directly to create an submap with spaces.
Next error message:
   JAVASCRIPT exeption:
   ERROR:
   TypeError: response_obj is null
Lets try without submap... same error message.
Lets try simple tekst file... same error message.
Lets try changing parameters in the backend, at the upload functionality tab.
(change map after upload; general => no uploading to map => general = yes)
Hey, new error message at the front:
{"error_summary": "invalid_access_token/...", "error": {".tag": "invalid_access_token"}}
hmm, I recognize this. Lets look... disconnect & reconnect try..pase dropbox code..
Yes, functionality is now correct. 
Conclusion: after changing parameters, reconnect is need, perhaps it could automate, and if not, after changing someting please disconnect and give the backenduser the message: please reconnect (or something..).

Now changing some parameters:
I don't want the upload functionality shown at the front end so I put hem out in de backend (second tab).
Yes... 2 map connections (same dropbox user) doesn't work anymore. LEt's reconnect...
Jep.. it works, looks buggy because I need to reconnect several times... same error messages.
Refresh.. refresh in the frontend and dropbox asks the permissions.
Hmm.. this looks unwanted. The connection fails, endusers (site visitors) get the question to authorisate at dropbox. But when dhey log in with their own login,... the software cannot find what he want..

Now, everything looks good, but after trying to download a file, I got the same error message.
Fout: 
{"error_summary": "invalid_access_token/.", "error": {".tag": "invalid_access_token"}}
after lots of trying, it seemt it does not work. Strange, once a time I had a succesfull download.

For sofar my findings.

**Comment by individual-it** [comment]
thank you for your report.
I can reproduce some upload problems, but not the invalid_access_token problems.
did you update from an old version or a complete new installation?
Could you please post a step by step (with screenshots) instruction how to reproduce that problem

**Comment by StephanEd75** [comment]
Hi Artur,

It was not a fresh install.
I can do a fresh one if you recommend.
Our you can look why our site does not work.
Should I do a new install?

Mvg Stephan Edelijn




Op wo 10 mei 2017 om 15:38 schreef Artur Neumann <notifications@github.com>

**Comment by individual-it** [comment]
yes please try a fresh install and use 4.0.ALPHA.2
I've just uploaded it to the same place where you did find the fist version

**Comment by individual-it** [comment]
this problems should be fixed.
Closing the issue. Please reopen if the issues still persist with ALPHA.3 version
