### ISSUE TITLE
After installing dropbox ALPHA3 new menu item tells: Component not exists

### ISSUE THREAD

**Issue by StephanEd75** [JankariTech/DropboxExtensionForJoomlaPublic#2]
After installing (fresh?, DB seems not empty) I got the message component does not exists after a menu item was created. It looks that the menu item is not published, but still it is.

Dropbox1b (Alias: dropbox1b)
Component 'com_dropbox' bestaat niet 

However, the basic functionality seems to work.
Besides that, it works also with dropbox shared folders.
So, almost good job!!

Afer install:
- check showing the dropbox files: I see that the left menu is in the dropbox list. See attachment.
- It seems that the dropbox doesn't take the default sorting from the options menu.
- Creating a submap with files, doesn't work (browser waits for going into the map)

**Comment by individual-it** [comment]
>  check showing the dropbox files: I see that the left menu is in the dropbox list. See attachment.

could you please upload a screenshot for that?

>   Creating a submap with files, doesn't work (browser waits for going into the map)

Could you please tell me what names of folders you are using in the extension and on dropbox. Capital/lower case?

**Comment by individual-it** [comment]
> It seems that the dropbox doesn't take the default sorting from the options menu.

where have you set the sorting? Global Options? Per Connection setting?
Please provide screen shots

**Comment by StephanEd75** [comment]
Screenshot that menu item could not be set as active (but still works)
![dropbox_component_not_active](https://cloud.githubusercontent.com/assets/20813491/26142430/c24d48f8-3ae0-11e7-8062-c3394b55fa80.jpg)

Showing the component in the frontend (now menu's come below, berhaps it depends which beowser is used)
![2017-05-17 09_26_33-dropbox1b - user menu below instead of right](https://cloud.githubusercontent.com/assets/20813491/26143218/6361a52e-3ae4-11e7-9d65-68a14fc42dbe.jpg)
![2017-05-17 09_29_02-dropbox1b - usermenu right and toer menu left](https://cloud.githubusercontent.com/assets/20813491/26143219/636305fe-3ae4-11e7-8920-ee254d50e818.jpg)



Submaps: Strange... now it works (perhaps slow caching website or something)
(I've tried several options, with-without spaces, capitalizing...)
Sorting: Works! I didn't look in the component (only the menu item)

**Comment by individual-it** [comment]
could you please send me a link to you page, so I can check what the problem is with the position of the menu.
And also an admin user for the test would be good, I would like to follow up the problem that the menu item cannot be set

**Comment by StephanEd75** [comment]
Hi Artur

Of course.

You can use:
user/pwd: larry / larry12#
at http://www.zwaluwendeventer.nl/administrator

In the front end, please login by clicking contact =>site gebruikers.
The user menu has two dropbox test links available for registered users.
See also the other bug, why the menu item is not valid. Perhaps you did it
already fixing for the first beta release..

Mvg Stephan Edelijn


Op wo 17 mei 2017 om 10:22 schreef Artur Neumann <notifications@github.com>

**Comment by pawelts1** [comment]
In Dropbox Manager when editing parameters each time they are set to "use global". Component doesn't save last changes.
![use global1](https://cloud.githubusercontent.com/assets/28792032/26223955/a25de9a8-3c20-11e7-943f-6b273d3db9e6.JPG)

**Comment by individual-it** [comment]
@StephanEd75 
Looked at your site and could not see that problem. So might be solved by current version
![1](https://cloud.githubusercontent.com/assets/2425577/26295938/f44d85e6-3ebb-11e7-998f-fb619ffa87fa.png)
![2](https://cloud.githubusercontent.com/assets/2425577/26295939/f44f4f52-3ebb-11e7-865b-2469c1ed58c5.png)

@pawelts1 I've opened a separate issue for that: #3
could you please report there what version of Joomla / PHP and the extension you are using?
And describe the steps to reproduce that issue
