### ISSUE TITLE
Files and folders not listed for connected folder

### ISSUE THREAD

**Issue by tntmartin** [JankariTech/DropboxExtensionForJoomlaPublic#4]
Hi Artur,
I have installed the dropbox plugin 4.0.2 on my site www.brfuddeholm.se.
I get everything to work, except the possibility to see whats inside my connected folder.
When I upload something from the homepage to the dropbox, the file show up at my dropbox-account, but everything is blank at the homepage.

I can give you access to the site if you need it. I have tried uninstall all the components, clear cache, delete entries in the database and install again. It doesnt work.

I'm running:
PHP-version | 7.0.20
Joomlaversion | Joomla! 3.7.2 

Best Regards,
Martin

**Comment by individual-it** [comment]
could you please post a link where I can test the file listing?

**Comment by tntmartin** [comment]
Hi Artur,
I found the problem. It was my template causing the problem,
I found a solution for it now.

Thank you

Best Regards,
Martin Löfgren
Tel. 0733-804681

På 26 juli 2017 till 14:36:02, Artur Neumann (notifications@github.com) skrev:

could you please post a link where I can test the file listing?
